//
//  TrackPreview.swift
//  Media-SUI
//
//  Created by KsArT on 21.01.2025.
//

import UIKit

struct TrackPreview {
    let tracks = [
        Track(
            id: "2204093",
            name: "Mocha | Slap House Music",
            duration: 217,
            artistID: "Praz_Khanal_(4)",
            artistName: "Praz Khanal",
            artistIdstr: "",
            albumName: "Mocha | Slap House Music",
            albumID: "",
            licenseCcurl: "",
            position: 1,
            releasedate: "2024-09-17",
            albumImage: "",
            audio: "https://prod-1.storage.jamendo.com/?trackid=2204093&format=mp31&from=5iO95DtdNpoVYs5r7KBuEQ%3D%3D%7CDQXfBwehdf4sWCbTkpEwag%3D%3D",
            audiodownload: "https://prod-1.storage.jamendo.com/download/track/2204093/mp32/",
            shorturl: "https://jamen.do/t/2204093",
            shareurl: "https://www.jamendo.com/track/2204093",
            waveform: [],
            image: UIImage(named: "Mocha___Slap_House_Music")?.pngData(),
            musicinfo: "",
            imageUrl: nil,
            songUrl: nil
        ),
        Track(
            id: "2161171",
            name: "Host",
            duration: 177,
            artistID: "",
            artistName: "Color Out",
            artistIdstr: "Color_Out",
            albumName: "Host / Therapy (In My Skin)",
            albumID: "",
            licenseCcurl: "",
            position: 0,
            releasedate: "",
            albumImage: "",
            audio: "",
            audiodownload: "",
            shorturl: "",
            shareurl: "",
            waveform: [],
            image: UIImage(named: "Lofi_Chillout_Hip_Hop_Beat")?.pngData(),
            musicinfo: "",
            imageUrl: nil,
            songUrl: nil
        ),
        Track(
            id: "1593988",
            name: "Lofi Chillout Hip Hop Beat",
            duration: 149,
            artistID: "",
            artistName: "Joystock",
            artistIdstr: "Dean_Caedab",
            albumName: "Lofi Chillout Hip Hop Beat",
            albumID: "",
            licenseCcurl: "",
            position: 0,
            releasedate: "2018-11-22",
            albumImage: "",
            audio: "",
            audiodownload: "",
            shorturl: "",
            shareurl: "",
            waveform: [],
            image: UIImage(named: "Lofi_Chillout_Hip_Hop_Beat")?.pngData(),
            musicinfo: "",
            imageUrl: nil,
            songUrl: nil
        ),
        Track(
            id: "1826189",
            name: "Not the One to Say (I Told You So) (24-bit Master)",
            duration: 235,
            artistID: "",
            artistName: "Cole Powell",
            artistIdstr: "Cole_Powell",
            albumName: "Not the One to Say (I Told You So) (24-bit Master)",
            albumID: "",
            licenseCcurl: "",
            position: 0,
            releasedate: "2021-01-23",
            albumImage: "",
            audio: "",
            audiodownload: "",
            shorturl: "",
            shareurl: "",
            waveform: [],
            image: UIImage(named: "Not_the_One_to_Say__I_Told_You_So___24-bit_Master_")?.pngData(),
            musicinfo: "",
            imageUrl: nil,
            songUrl: nil
        ),
        Track(
            id: "2221139",
            name: "Lose My Rose",
            duration: 199,
            artistID: "",
            artistName: "Ed Napoli",
            artistIdstr: "ednapoli",
            albumName: "Lose My Rose",
            albumID: "",
            licenseCcurl: "",
            position: 0,
            releasedate: "2024-12-05",
            albumImage: "",
            audio: "",
            audiodownload: "",
            shorturl: "",
            shareurl: "",
            waveform: [],
            image: UIImage(named: "Lose_My_Rose")?.pngData(),
            musicinfo: "",
            imageUrl: nil,
            songUrl: nil
        ),
        Track(
            id: "2137882",
            name: "Bad Intentions",
            duration: 181,
            artistID: "",
            artistName: "Bessonn&amp;sa",
            artistIdstr: "bessonnitsa",
            albumName: "Bad Intentions",
            albumID: "",
            licenseCcurl: "",
            position: 0,
            releasedate: "2023-12-10",
            albumImage: "",
            audio: "",
            audiodownload: "",
            shorturl: "",
            shareurl: "",
            waveform: [],
            image: UIImage(named: "Bad_Intentions")?.pngData(),
            musicinfo: "",
            imageUrl: nil,
            songUrl: nil
        ),
    ]
}
